
package com.ordg.blueb.pos.dashboard;

/**
 *
 * @author Hp
 */
public class NotificationBar extends javax.swing.JPanel {

    /**
     * Creates new form NotificationBar
     */
    public NotificationBar(String p,String Message) {
        initComponents();
        
        String iconName="information_24px";
        if (p.toUpperCase().equals("ERROR"))
                {
                   iconName="error_24px"; 
                }
        if (p.toUpperCase().equals("MESSAGE"))
                {
                   iconName="message_24px"; 
                }
        
        messageText.setText(Message);
      //  MessageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ordg/resources/abstract-user-flat-4.png"))); // NOI18N
        MessageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ordg/resources/"+iconName+".png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessageIcon = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 0));
        messageText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(2147483647, 25));
        setMinimumSize(new java.awt.Dimension(575, 18));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        MessageIcon.setBackground(new java.awt.Color(255, 255, 255));
        add(MessageIcon);
        add(filler1);

        messageText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        messageText.setText("MessageText");
        messageText.setBorder(null);
        messageText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        messageText.setEnabled(false);
        messageText.setFocusable(false);
        add(messageText);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MessageIcon;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField messageText;
    // End of variables declaration//GEN-END:variables
}
